version: "3"

services:
  users-database:
    image: postgres
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_EXTERNAL_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${DB_HOST}:${DB_EXTERNAL_PORT}"]
      interval: 10s
      timeout: 2s
      retries: 5
  users-server:
    volumes:
      - ../../:/usr/src/app
      - /usr/src/app/node_modules/
    environment:
      - NODE_ENV=${NODE_ENV}
      - WATCHPACK_POLLING=true
    env_file:
      - ./.env
    command: bash -c "if [ $NODE_ENV == 'testing' ]; then pnpm run test:e2e; else pnpm run start:dev users; fi;"
    build: 
      context: ../../
      dockerfile: ./apps/users/Dockerfile
    depends_on:
      - users-database