version: "3"

services:
  users-server:
    volumes:
      - ../../:/usr/src/app
      - /usr/src/app/node_modules/
    environment:
      - NODE_ENV=${NODE_ENV}
      - WATCHPACK_POLLING=true
    env_file:
      - ./.env
    command: bash -c "if [ $NODE_ENV == 'testing' ]; then pnpm run test:e2e; else pnpm run start:dev users; fi;"
    build: 
      context: ../../
      dockerfile: ./apps/users/Dockerfile